/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/umbraco/delivery/api/v2/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetContent2.0"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/umbraco/delivery/api/v2/content/item/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetContentItemByPath2.0"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/umbraco/delivery/api/v2/content/item/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetContentItemById2.0"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/umbraco/delivery/api/v2/content/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetContentItems2.0"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/umbraco/delivery/api/v2/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetMedia2.0"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/umbraco/delivery/api/v2/media/item/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetMediaItemByPath2.0"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/umbraco/delivery/api/v2/media/item/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetMediaItemById2.0"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/umbraco/delivery/api/v2/media/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetMediaItems2.0"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiBlockGridAreaModel: {
            alias: string;
            /** Format: int32 */
            rowSpan: number;
            /** Format: int32 */
            columnSpan: number;
            items: components["schemas"]["ApiBlockGridItemModel"][];
        };
        ApiBlockGridItemModel: components["schemas"]["ApiBlockItemModel"] & {
            /** Format: int32 */
            rowSpan?: number;
            /** Format: int32 */
            columnSpan?: number;
            /** Format: int32 */
            areaGridColumns?: number;
            areas?: components["schemas"]["ApiBlockGridAreaModel"][];
        };
        ApiBlockItemModel: {
            content: components["schemas"]["IApiElementModel"];
            settings?: components["schemas"]["IApiElementModel"];
        };
        ApiBlockListModel: {
            items: (components["schemas"]["ApiBlockItemModel"] | components["schemas"]["ApiBlockGridItemModel"])[];
        };
        ApiContentRouteModel: {
            path: string;
            queryString?: string | null;
            startItem: components["schemas"]["ApiContentStartItemModel"];
        };
        ApiContentStartItemModel: {
            /** Format: uuid */
            id: string;
            path: string;
        };
        ApiLinkModel: {
            readonly url?: string | null;
            readonly queryString?: string | null;
            readonly title?: string | null;
            readonly target?: string | null;
            /** Format: uuid */
            readonly destinationId?: string | null;
            readonly destinationType?: string | null;
            readonly route?: components["schemas"]["ApiContentRouteModel"] | null;
            linkType: components["schemas"]["LinkTypeModel"];
        };
        BlockDisplaySettingsElementModel: {
            properties?: components["schemas"]["BlockDisplaySettingsPropertiesModel"];
        } & (Omit<components["schemas"]["IApiElementModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "blockDisplaySettings";
        });
        BlockDisplaySettingsPropertiesModel: {
            constrainToContentColumn?: boolean | null;
            topPadding?: string | null;
            bottomPadding?: string | null;
        };
        BlogArticleContentModel: {
            properties?: components["schemas"]["BlogArticlePropertiesModel"];
        } & (Omit<components["schemas"]["IApiContentModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "blogArticle";
        });
        BlogArticleContentResponseModel: Omit<components["schemas"]["IApiContentResponseModelBase"], "contentType"> & Omit<components["schemas"]["BlogArticleContentModel"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "blogArticle";
        };
        BlogArticlePropertiesModel: components["schemas"]["CompositionStandardContentPropertiesModel"] & components["schemas"]["CompositionPageMetadataPropertiesModel"] & components["schemas"]["CompositionPageHeaderPropertiesModel"];
        BlogContentModel: {
            properties?: components["schemas"]["BlogPropertiesModel"];
        } & (Omit<components["schemas"]["IApiContentModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "blog";
        });
        BlogContentResponseModel: Omit<components["schemas"]["IApiContentResponseModelBase"], "contentType"> & Omit<components["schemas"]["BlogContentModel"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "blog";
        };
        BlogListingBlockElementModel: {
            properties?: components["schemas"]["BlogListingBlockPropertiesModel"];
        } & (Omit<components["schemas"]["IApiElementModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "blogListingBlock";
        });
        BlogListingBlockPropertiesModel: {
            /** Format: int32 */
            pageSize?: number | null;
        };
        BlogPropertiesModel: components["schemas"]["CompositionStandardContentPropertiesModel"] & components["schemas"]["CompositionPageMetadataPropertiesModel"] & components["schemas"]["CompositionPageHeaderPropertiesModel"];
        CallToActionBlockElementModel: {
            properties?: components["schemas"]["CallToActionBlockPropertiesModel"];
        } & (Omit<components["schemas"]["IApiElementModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "callToActionBlock";
        });
        CallToActionBlockPropertiesModel: {
            image?: components["schemas"]["IApiMediaWithCropsModel"][] | null;
            heading?: string | null;
            text?: components["schemas"]["RichTextModel"];
            actions?: components["schemas"]["ApiLinkModel"][] | null;
        };
        CallToActionPageHeaderElementModel: {
            properties?: components["schemas"]["CallToActionPageHeaderPropertiesModel"];
        } & (Omit<components["schemas"]["IApiElementModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "callToActionPageHeader";
        });
        CallToActionPageHeaderPropertiesModel: components["schemas"]["HeroBlockPropertiesModel"];
        CodeEmbedBlockElementModel: {
            properties?: components["schemas"]["CodeEmbedBlockPropertiesModel"];
        } & (Omit<components["schemas"]["IApiElementModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "codeEmbedBlock";
        });
        CodeEmbedBlockPropertiesModel: {
            code?: string | null;
            language?: string | null;
        };
        CompositionPageHeaderElementModel: {
            properties?: components["schemas"]["CompositionPageHeaderPropertiesModel"];
        } & (Omit<components["schemas"]["IApiElementModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "compositionPageHeader";
        });
        CompositionPageHeaderPropertiesModel: {
            pageHeader?: components["schemas"]["ApiBlockItemModel"] | components["schemas"]["ApiBlockGridItemModel"];
        };
        CompositionPageMetadataElementModel: {
            properties?: components["schemas"]["CompositionPageMetadataPropertiesModel"];
        } & (Omit<components["schemas"]["IApiElementModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "compositionPageMetadata";
        });
        CompositionPageMetadataPropertiesModel: {
            metaTitle?: string | null;
            metaDescription?: string | null;
            openGraphImage?: components["schemas"]["IApiMediaWithCropsModel"][] | null;
        };
        CompositionStandardContentElementModel: {
            properties?: components["schemas"]["CompositionStandardContentPropertiesModel"];
        } & (Omit<components["schemas"]["IApiElementModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "compositionStandardContent";
        });
        CompositionStandardContentPropertiesModel: {
            pageContent?: components["schemas"]["ApiBlockListModel"];
        };
        ContentPageContentModel: {
            properties?: components["schemas"]["ContentPagePropertiesModel"];
        } & (Omit<components["schemas"]["IApiContentModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "contentPage";
        });
        ContentPageContentResponseModel: Omit<components["schemas"]["IApiContentResponseModelBase"], "contentType"> & Omit<components["schemas"]["ContentPageContentModel"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "contentPage";
        };
        ContentPagePropertiesModel: components["schemas"]["CompositionStandardContentPropertiesModel"] & components["schemas"]["CompositionPageMetadataPropertiesModel"] & components["schemas"]["CompositionPageHeaderPropertiesModel"];
        HeaderContentModel: {
            properties?: components["schemas"]["HeaderPropertiesModel"];
        } & (Omit<components["schemas"]["IApiContentModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "header";
        });
        HeaderContentResponseModel: Omit<components["schemas"]["IApiContentResponseModelBase"], "contentType"> & Omit<components["schemas"]["HeaderContentModel"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "header";
        };
        HeaderPropertiesModel: {
            logo?: components["schemas"]["IApiMediaWithCropsModel"][] | null;
            siteName?: string | null;
            links?: components["schemas"]["ApiBlockListModel"];
        };
        HeroBlockElementModel: {
            properties?: components["schemas"]["HeroBlockPropertiesModel"];
        } & (Omit<components["schemas"]["IApiElementModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "heroBlock";
        });
        HeroBlockPropertiesModel: {
            heading?: string | null;
            subheading?: string | null;
            backgroundImage?: components["schemas"]["IApiMediaWithCropsModel"][] | null;
            ctaLink?: components["schemas"]["ApiLinkModel"][] | null;
        };
        HomepageContentModel: {
            properties?: components["schemas"]["HomepagePropertiesModel"];
        } & (Omit<components["schemas"]["IApiContentModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "homepage";
        });
        HomepageContentResponseModel: Omit<components["schemas"]["IApiContentResponseModelBase"], "contentType"> & Omit<components["schemas"]["HomepageContentModel"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "homepage";
        };
        HomepagePropertiesModel: components["schemas"]["CompositionStandardContentPropertiesModel"] & components["schemas"]["CompositionPageMetadataPropertiesModel"];
        HttpValidationProblemDetails: components["schemas"]["ProblemDetails"] & ({
            errors?: {
                [key: string]: string[];
            };
        } & {
            [key: string]: unknown;
        });
        IApiContentModel: components["schemas"]["HomepageContentModel"] | components["schemas"]["ContentPageContentModel"] | components["schemas"]["BlogContentModel"] | components["schemas"]["BlogArticleContentModel"] | components["schemas"]["SettingsContentModel"] | components["schemas"]["HeaderContentModel"];
        IApiContentModelBase: {
            /** Format: uuid */
            readonly id: string;
            readonly contentType: string;
            readonly name?: string | null;
            /** Format: date-time */
            readonly createDate: string;
            /** Format: date-time */
            readonly updateDate: string;
            readonly route: components["schemas"]["ApiContentRouteModel"];
        } & Omit<WithRequired<components["schemas"]["IApiElementModelBase"], "contentType" | "id">, "contentType">;
        IApiContentResponseModel: components["schemas"]["HomepageContentResponseModel"] | components["schemas"]["ContentPageContentResponseModel"] | components["schemas"]["BlogContentResponseModel"] | components["schemas"]["BlogArticleContentResponseModel"] | components["schemas"]["SettingsContentResponseModel"] | components["schemas"]["HeaderContentResponseModel"];
        IApiContentResponseModelBase: {
            /** Format: uuid */
            readonly id: string;
            readonly contentType: string;
            readonly name?: string | null;
            /** Format: date-time */
            readonly createDate: string;
            /** Format: date-time */
            readonly updateDate: string;
            readonly route: components["schemas"]["ApiContentRouteModel"];
            readonly cultures: {
                [key: string]: components["schemas"]["ApiContentRouteModel"];
            };
        } & Omit<WithRequired<components["schemas"]["IApiContentModelBase"], "contentType" | "createDate" | "id" | "route" | "updateDate">, "contentType">;
        IApiElementModel: components["schemas"]["CodeEmbedBlockElementModel"] | components["schemas"]["ImageGalleryBlockElementModel"] | components["schemas"]["TextBlockElementModel"] | components["schemas"]["VideoEmbedBlockElementModel"] | components["schemas"]["CompositionStandardContentElementModel"] | components["schemas"]["CompositionPageMetadataElementModel"] | components["schemas"]["HeroBlockElementModel"] | components["schemas"]["NavigationAreaElementModel"] | components["schemas"]["NavigationTitleElementModel"] | components["schemas"]["NaviationTitleLinkElementModel"] | components["schemas"]["BlockDisplaySettingsElementModel"] | components["schemas"]["BlogListingBlockElementModel"] | components["schemas"]["CompositionPageHeaderElementModel"] | components["schemas"]["ImageOffsetPageHeaderElementModel"] | components["schemas"]["CallToActionPageHeaderElementModel"] | components["schemas"]["CallToActionBlockElementModel"];
        IApiElementModelBase: {
            /** Format: uuid */
            readonly id: string;
            readonly contentType: string;
        };
        IApiMediaWithCropsModel: {
            /** Format: uuid */
            readonly id: string;
            readonly name: string;
            readonly mediaType: string;
            readonly url: string;
            readonly extension?: string | null;
            /** Format: int32 */
            readonly width?: number | null;
            /** Format: int32 */
            readonly height?: number | null;
            /** Format: int32 */
            readonly bytes?: number | null;
            readonly properties: {
                [key: string]: unknown;
            };
            focalPoint?: components["schemas"]["ImageFocalPointModel"];
            readonly crops?: components["schemas"]["ImageCropModel"][] | null;
        };
        IApiMediaWithCropsResponseModel: {
            /** Format: uuid */
            readonly id: string;
            readonly name: string;
            readonly mediaType: string;
            readonly url: string;
            readonly extension?: string | null;
            /** Format: int32 */
            readonly width?: number | null;
            /** Format: int32 */
            readonly height?: number | null;
            /** Format: int32 */
            readonly bytes?: number | null;
            readonly properties: {
                [key: string]: unknown;
            };
            focalPoint: components["schemas"]["ImageFocalPointModel"];
            readonly crops?: components["schemas"]["ImageCropModel"][] | null;
            readonly path: string;
            /** Format: date-time */
            readonly createDate: string;
            /** Format: date-time */
            readonly updateDate: string;
        };
        ImageCropCoordinatesModel: {
            /** Format: double */
            x1: number;
            /** Format: double */
            y1: number;
            /** Format: double */
            x2: number;
            /** Format: double */
            y2: number;
        };
        ImageCropModel: {
            alias?: string | null;
            /** Format: int32 */
            width: number;
            /** Format: int32 */
            height: number;
            coordinates?: components["schemas"]["ImageCropCoordinatesModel"];
        };
        ImageFocalPointModel: {
            /** Format: double */
            left: number;
            /** Format: double */
            top: number;
        };
        ImageGalleryBlockElementModel: {
            properties?: components["schemas"]["ImageGalleryBlockPropertiesModel"];
        } & (Omit<components["schemas"]["IApiElementModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "imageGalleryBlock";
        });
        ImageGalleryBlockPropertiesModel: {
            images?: components["schemas"]["IApiMediaWithCropsModel"][] | null;
        };
        ImageOffsetPageHeaderElementModel: {
            properties?: components["schemas"]["ImageOffsetPageHeaderPropertiesModel"];
        } & (Omit<components["schemas"]["IApiElementModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "imageOffsetPageHeader";
        });
        ImageOffsetPageHeaderPropertiesModel: {
            image?: components["schemas"]["IApiMediaWithCropsModel"][] | null;
        };
        /** @enum {string} */
        LinkTypeModel: "Content" | "Media" | "External";
        NaviationTitleLinkElementModel: {
            properties?: components["schemas"]["NaviationTitleLinkPropertiesModel"];
        } & (Omit<components["schemas"]["IApiElementModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "naviationTitleLink";
        });
        NaviationTitleLinkPropertiesModel: {
            titleLink?: components["schemas"]["ApiLinkModel"][] | null;
        };
        NavigationAreaElementModel: {
            properties?: components["schemas"]["NavigationAreaPropertiesModel"];
        } & (Omit<components["schemas"]["IApiElementModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "navigationArea";
        });
        NavigationAreaPropertiesModel: {
            title?: components["schemas"]["ApiBlockItemModel"] | components["schemas"]["ApiBlockGridItemModel"];
            links?: components["schemas"]["ApiLinkModel"][] | null;
        };
        NavigationTitleElementModel: {
            properties?: components["schemas"]["NavigationTitlePropertiesModel"];
        } & (Omit<components["schemas"]["IApiElementModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "navigationTitle";
        });
        NavigationTitlePropertiesModel: {
            title?: string | null;
        };
        PagedIApiContentResponseModel: {
            /** Format: int64 */
            total: number;
            items: components["schemas"]["IApiContentResponseModel"][];
        };
        PagedIApiMediaWithCropsResponseModel: {
            /** Format: int64 */
            total: number;
            items: components["schemas"]["IApiMediaWithCropsResponseModel"][];
        };
        ProblemDetails: {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
        } & {
            [key: string]: unknown;
        };
        RichTextModel: {
            markup: string;
            blocks: (components["schemas"]["ApiBlockItemModel"] | components["schemas"]["ApiBlockGridItemModel"])[];
        };
        SettingsContentModel: {
            contentType: "SettingsContentModel";
            properties?: components["schemas"]["SettingsPropertiesModel"];
        } & Omit<components["schemas"]["IApiContentModelBase"], "contentType">;
        SettingsContentResponseModel: {
            contentType: "SettingsContentResponseModel";
        } & (Omit<components["schemas"]["IApiContentResponseModelBase"], "contentType"> & Omit<components["schemas"]["SettingsContentModel"], "contentType">);
        SettingsPropertiesModel: Record<string, never>;
        TextBlockElementModel: {
            properties?: components["schemas"]["TextBlockPropertiesModel"];
        } & (Omit<components["schemas"]["IApiElementModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "textBlock";
        });
        TextBlockPropertiesModel: {
            text?: components["schemas"]["RichTextModel"];
        };
        VideoEmbedBlockElementModel: {
            properties?: components["schemas"]["VideoEmbedBlockPropertiesModel"];
        } & (Omit<components["schemas"]["IApiElementModelBase"], "contentType"> & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            contentType: "videoEmbedBlock";
        });
        VideoEmbedBlockPropertiesModel: {
            url?: string | null;
            title?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "GetContent2.0": {
        parameters: {
            query?: {
                /** @description Specifies the content items to fetch. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this. */
                fetch?: string;
                /** @description Defines how to filter the fetched content items. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this. */
                filter?: string[];
                /** @description Defines how to sort the found content items. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this. */
                sort?: string[];
                /** @description Specifies the number of found content items to skip. Use this to control pagination of the response. */
                skip?: number;
                /** @description Specifies the number of found content items to take. Use this to control pagination of the response. */
                take?: number;
                /** @description Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this. */
                expand?: string;
                /** @description Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this. */
                fields?: string;
            };
            header?: {
                /** @description Defines the language to return. Use this when querying language variant content items. */
                "Accept-Language"?: string;
                /** @description Defines the segment to return. Use this when querying segment variant content items. */
                "Accept-Segment"?: string;
                /** @description API key specified through configuration to authorize access to the API. */
                "Api-Key"?: string;
                /** @description Whether to request draft content. */
                Preview?: boolean;
                /** @description URL segment or GUID of a root content item. */
                "Start-Item"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedIApiContentResponseModel"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"] | components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "GetContentItemByPath2.0": {
        parameters: {
            query?: {
                /** @description Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this. */
                expand?: string;
                /** @description Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this. */
                fields?: string;
            };
            header?: {
                /** @description Defines the language to return. Use this when querying language variant content items. */
                "Accept-Language"?: string;
                /** @description Defines the segment to return. Use this when querying segment variant content items. */
                "Accept-Segment"?: string;
                /** @description API key specified through configuration to authorize access to the API. */
                "Api-Key"?: string;
                /** @description Whether to request draft content. */
                Preview?: boolean;
                /** @description URL segment or GUID of a root content item. */
                "Start-Item"?: string;
            };
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IApiContentResponseModel"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "GetContentItemById2.0": {
        parameters: {
            query?: {
                /** @description Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this. */
                expand?: string;
                /** @description Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this. */
                fields?: string;
            };
            header?: {
                /** @description Defines the language to return. Use this when querying language variant content items. */
                "Accept-Language"?: string;
                /** @description Defines the segment to return. Use this when querying segment variant content items. */
                "Accept-Segment"?: string;
                /** @description API key specified through configuration to authorize access to the API. */
                "Api-Key"?: string;
                /** @description Whether to request draft content. */
                Preview?: boolean;
                /** @description URL segment or GUID of a root content item. */
                "Start-Item"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IApiContentResponseModel"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "GetContentItems2.0": {
        parameters: {
            query?: {
                id?: string[];
                /** @description Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this. */
                expand?: string;
                /** @description Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this. */
                fields?: string;
            };
            header?: {
                /** @description Defines the language to return. Use this when querying language variant content items. */
                "Accept-Language"?: string;
                /** @description Defines the segment to return. Use this when querying segment variant content items. */
                "Accept-Segment"?: string;
                /** @description API key specified through configuration to authorize access to the API. */
                "Api-Key"?: string;
                /** @description Whether to request draft content. */
                Preview?: boolean;
                /** @description URL segment or GUID of a root content item. */
                "Start-Item"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IApiContentResponseModel"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "GetMedia2.0": {
        parameters: {
            query?: {
                /** @description Specifies the media items to fetch. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this. */
                fetch?: string;
                /** @description Defines how to filter the fetched media items. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this. */
                filter?: string[];
                /** @description Defines how to sort the found media items. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this. */
                sort?: string[];
                /** @description Specifies the number of found media items to skip. Use this to control pagination of the response. */
                skip?: number;
                /** @description Specifies the number of found media items to take. Use this to control pagination of the response. */
                take?: number;
                /** @description Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this. */
                expand?: string;
                /** @description Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this. */
                fields?: string;
            };
            header?: {
                /** @description API key specified through configuration to authorize access to the API. */
                "Api-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedIApiMediaWithCropsResponseModel"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"] | components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    "GetMediaItemByPath2.0": {
        parameters: {
            query?: {
                /** @description Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this. */
                expand?: string;
                /** @description Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this. */
                fields?: string;
            };
            header?: {
                /** @description API key specified through configuration to authorize access to the API. */
                "Api-Key"?: string;
            };
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IApiMediaWithCropsResponseModel"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "GetMediaItemById2.0": {
        parameters: {
            query?: {
                /** @description Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this. */
                expand?: string;
                /** @description Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this. */
                fields?: string;
            };
            header?: {
                /** @description API key specified through configuration to authorize access to the API. */
                "Api-Key"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IApiMediaWithCropsResponseModel"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "GetMediaItems2.0": {
        parameters: {
            query?: {
                id?: string[];
                /** @description Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this. */
                expand?: string;
                /** @description Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this. */
                fields?: string;
            };
            header?: {
                /** @description API key specified through configuration to authorize access to the API. */
                "Api-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IApiMediaWithCropsResponseModel"][];
                };
            };
        };
    };
}
type WithRequired<T, K extends keyof T> = T & {
    [P in K]-?: T[P];
};
